name: Deploy Terraform

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'ci/terraform/*'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/*.yml'
      - 'ci/terraform/*'
env:
  GITHUB_TOKEN: ${{ secrets.GITHBU_TOKEN }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform-plan:
    name: TF plan-apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: release
      - name: Terraform Plan
        if: ${{ github.event_name == 'pull_request' }}
        id: plan
        uses: dflook/terraform-plan@v1.34.0
        with:
          add_github_comment: changes-only
          path: release/ci/terraform
          label: tf-plan
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        id: aply
        uses: dflook/terraform-apply@v1.34.0
        with:
          add_github_comment: changes-only
          path: release/ci/terraform
          label: tf-plan
